ADD: Payload category to support Actions
BlueWallet/GroundControl pull request #289
Opened 2024-10-27 01:26 UTC by marcosrdz

2024-10-27 10:01 UTC, Overtorment requested changes
first, what youre trying to achieve - you can  just check tht payload has `.txid` field on the client.
second, youre hardcoding thevalue, and instead i think youshould have modified definitions of specific notfications in `openapi.yaml`, to add a constant field:

```
        constantField:
          type: "string"
          const: "constantValue"
          description: "This is a constant field with a single value"
```

and then re-generate ts files from  that openapi spec.

but option 1 is easier

2024-10-27 15:31 UTC, marcosrdz commented
> first, what youre trying to achieve - you can just check tht payload has `.txid` field on the client. second, youre hardcoding thevalue, and instead i think youshould have modified definitions of specific notfications in `openapi.yaml`, to add a constant field:
> 
> ```
>         constantField:
>           type: "string"
>           const: "constantValue"
>           description: "This is a constant field with a single value"
> ```
> 
> and then re-generate ts files from that openapi spec.
> 
> but option 1 is easier

Option 1 is not possible. Client expects it from server.

2024-10-27 18:37 UTC, marcosrdz commented
@Overtorment  lmk if I need to change anythin

2024-10-27 21:38 UTC, Overtorment commented
Why option 1 is not ok? Payload from the server for those pish types will always have a txid field

2024-10-27 21:40 UTC, marcosrdz commented
> Why option 1 is not ok? Payload from the server for those pish types will always have a txid field

AppDelegate.mm requires the payload it receives from the server to contain the "category" property.  if it doesnt exist or if its empty it will not display the buttons.

2024-10-30 10:56 UTC, Overtorment commented
is that a requirement by apple? or its up to us to change? cause frankly, modifying client is easier than server in this case

2024-10-30 11:02 UTC, marcosrdz commented
> is that a requirement by apple? or its up to us to change? cause frankly, modifying client is easier than server in this case

Its a requirement. Client has to receive it on the payload

2024-10-31 12:40 UTC, Overtorment commented
> > is that a requirement by apple? or its up to us to change? cause frankly, modifying client is easier than server in this case
> 
> Its a requirement. Client has to receive it on the payload. Otherwise a compromised app could intercept it

wtf. post docs link pls

2024-10-31 12:44 UTC, marcosrdz commented
> > > is that a requirement by apple? or its up to us to change? cause frankly, modifying client is easier than server in this case
> 
> > 
> 
> > Its a requirement. Client has to receive it on the payload. Otherwise a compromised app could intercept it
> 
> 
> 
> wtf. post docs link pls

https://developer.apple.com/documentation/usernotifications/declaring-your-actionable-notification-types



For LOCAL notifications you can do do locally. Not for remote

2024-10-31 13:15 UTC, marcosrdz commented
https://developer.apple.com/documentation/usernotifications/unnotificationcategory

To apply category objects to your notifications, include the category’s identifier string in the payload of any notifications you create. For local notifications, put this string in the [categoryIdentifier](https://developer.apple.com/documentation/usernotifications/unmutablenotificationcontent/categoryidentifier) property of the [UNMutableNotificationContent](https://developer.apple.com/documentation/usernotifications/unmutablenotificationcontent) object that you use to specify the notification’s content. For remote notifications, use this string as the value of the category key in the aps dictionary of your payload.

2024-11-03 20:36 UTC, marcosrdz commented
@Overtorment  any updates?

2026-07-22 10:25 UTC, closed without merging